package demo.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import demo.domain.model.ModelData;
import demo.domain.model.ModelDataExample;


@Repository
@Mapper
public interface RepositoryData {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	long countByExample(ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	int deleteByExample(ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	int insert(ModelData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	int insertSelective(ModelData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	List<ModelData> selectByExample(ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	int updateByExampleSelective(@Param("record") ModelData record, @Param("example") ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table data
	 * @mbg.generated  Fri May 08 20:28:46 JST 2020
	 */
	int updateByExample(@Param("record") ModelData record, @Param("example") ModelDataExample example);
}